In [2]:
import numpy as np

In [4]:
berlin=np.array([100,120,90]) #hotel,food,transport
paris=np.array([200,210,180])
rome=np.array([210,230,120])

In [5]:
#Total per city
sum_berlin = berlin.sum()
sum_paris = berlin.sum()
sum_rome = rome.sum()

print(sum_berlin,sum_paris,sum_rome)

310 310 560


In [9]:
#Average Trip Cost
avg_berlin = berlin.mean()
avg_paris = paris.mean()
avg_rome  = rome.mean()
avg_cost = np.array([avg_berlin,avg_paris,avg_rome]).mean()

print(avg_cost)

162.2222222222222


In [10]:
# Average cost of Hotel and Food in all 3 cities and
narray = np.array([berlin,paris,rome])
narray

array([[100, 120,  90],
       [200, 210, 180],
       [210, 230, 120]])

In [11]:
array_mean_columns = narray.mean(axis=0)
array_mean_columns

array([170.        , 186.66666667, 130.        ])

In [12]:
array_mean_row = narray.mean(axis=1)
array_mean_row

array([103.33333333, 196.66666667, 186.66666667])

In [14]:
factory_data=[[50, 30],   # Factory 1
[40, 60],   # Factory 2
[70, 20]]   # Factory 3
factory_data = np.array(factory_data)

Cost per product:

    A-> INR 5
    B-> INR 8
Calculate total cost per factory

Calculate total units of A and B across all factories

What is the overall cost?

In [19]:
cost_per_product=np.array([5,8])

In [24]:
# Calculate total cost per factory
total_cost_per_factory = np.dot(factory_data,cost_per_product)

In [22]:
# Calculate total units of A and B across all factories
np.sum(factory_data,axis=0)


array([160, 110])

In [25]:
# What is the overall cost?
np.sum(total_cost_per_factory)

1680

In [ ]:
# x + 2y + z = 10
# 3x + y + 2z = 18
# 2x + 3y + 3z = 27
# 1.Represent this in NumPy arrays

# 2.Solve it using np.linalg.solve()

In [34]:
A = np.array([[1,2,1],[3,1,2],[2,3,3]])
A

array([[1, 2, 1],
       [3, 1, 2],
       [2, 3, 3]])

In [36]:
b = np.array([10,18,27])
b

array([10, 18, 27])

In [37]:
np.linalg.solve(A,b)

array([0.5       , 0.83333333, 7.83333333])

In [ ]:
#  Question 1: Element-wise Operations (Basic)
# Create a NumPy array of numbers from 1 to 10.
# Now:

# Square each element
# Replace all even numbers with 0
# Print the final array

In [40]:
basic =np.array([range(0,11)])
basic

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [42]:
# Square each element
square_basic =np.square(basic)
square_basic

array([[  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100]])

In [44]:
# Replace all even numbers with 0
square_basic[square_basic % 2 == 0 ] =0
square_basic

array([[ 0,  1,  0,  9,  0, 25,  0, 49,  0, 81,  0]])

In [45]:
# 📗 Question 2: Matrix Diagonal & Trace (Intermediate)

matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
np.diagonal(matrix)

array([10, 50, 90])

In [46]:
np.trace(matrix)

150

In [51]:
# Question 3: Boolean Masking (Intermediate)
temps = np.array([22, 25, 19, 30, 28, 15, 24], dtype=float)
# Filter out all temperatures above 25°C
# Replace all values < 20°C with np.nan

In [52]:
above_25 = temps[temps > 25]
above_25

array([30., 28.])

In [53]:
temps[temps < 20] = np.nan
temps

array([22., 25., nan, 30., 28., nan, 24.])